components/story-element.js, rollup.config.js
* Refactor story element component
* Add support for render component prop for story elements
=> Story element render component

components/social-share.js
1. Made hashtags an optional parameter
2. Not slicing title, instead letting the user decide what to do for
character limits.
=> Changes to social share component.

components/story-element.js
- Add alt to `StoryElementImage`
=> Add alt tag to story element image component

README.md, components/collection.js, index.js, utils.js
1. Added collection component to render collection templates
2. Added utility method to load preview data
=> Collection loader

components/review-rating/review-rating.js, package-lock.json, package.json
- Add unique key to children
- Return null if value less than `0.1`
=> Refactor rev-story component

components/search-box.js, package-lock.json, package.json
Search box on much should be focused for better UI experience
=> Refactor search box to focus on mount

components/load-more-button.js, components/load-more-stories-base.js, components/wrap-collection-layout.js, index.js
Along with other updates in `load-more-stories-base.js` to support customisable `offset` and `storiesOnClick`(number of stories to load on clicking load more button)
=> Add LoadMoreButton component

components/story-elements/table.js
**Issue**: TableView component is trying to use map function on objects. Since map function is not available on the object, TableView component is breaking.
**context**: In the initial implementation React table was used and data was passed in the form of array of objects. Recently React table was removed and re-implemented using table element. While re-implementing, row data which comes as object was not handled properly.
=> Fix table element issue

components/wrap-collection-layout.js
update how a component is returned if no loadmore
=> Remove maybeWrapLoadMore from reduce

components/load-more-stories-base.js, components/wrap-collection-layout.js
- initial_stories_load_count to 6
- subsequent_stories_load_count to 10
=> Add default values

components/infinite-story-base.js
Set SEO metatitle and fallback to story title
=> #31 Set SEO metatitle and fallback to story title

components/link.js, package-lock.json, package.json
Add support open a link in a new tab.
Use case : Story type -`news elsewhere`
=> Update link component to support external links

package-lock.json, package.json, src/components/lazy-load-images.js
=> fix(lazy-load): Implemented checks to lazy load images on UC browser

package-lock.json, package.json, src/components/infinite-story-base.js
Pass story and config to InfiniteStoryBase component
=> feat: Pass story and config to InfiniteStoryBase component

src/components/story-elements/table.js
The regression came while a refactor was done to remove lodash.
=> fix(table story element): fix breaking table story element

src/components/load-more-stories-base.js
This is needed because we need author stories for vikatan. The urls format is /api/v1/authors/<author_id>/collection.
So I have made a provision to accept a type of collection and collection id and stories will be returned based on these inputs.
=> feat(Query for Author): If passed Author id query Author API

README.md, src/components/collection.js
Lazy collection to accept extra props to be passed to the template.
=> feat(LazyCollection accept arbitrary props): lazy collection to accept extra props to be passed to the collection templates

.babelrc, README.md, package-lock.json, package.json, src/components/story-element.js, src/components/story-elements/youtube.js, src/utils.js
Qlitics events are to be fired for every story element that is scrolled into view.
=> feat(qlitics): qlitics for story-element-view, story-element action

src/components/dfp-ad.js
- expose a dfp function to refresh ads
=> feat(DfpAd Refresh): expose a dfp function to refresh ads

package-lock.json, package.json
=> fix: update quintype-js to 1.2.0

package-lock.json, package.json, src/components/story-element.js
=> feat(image-caption): add wrapper for image-caption and attribution in responsiveImage

src/components/story-element.js
issue : https://github.com/quintype/ace-support/issues/420
also read story element text lang change for NH
=> refactor : also read story element text lang change for NH

src/components/wrap-collection-layout.js
Pass allowComponentWithoutStories as true to render collection without a dummy story
=> feat: Add optional params for wrapCollectionLayout function

src/components/access-type.js
Added function in access-type.js to support `AT validate coupon`
=> (feat) : Added function to validate AT coupon

package-lock.json, package.json, src/components/access-type.js
1. refactored code to support multiple params, currently, I have added obj to support gift subscription and coupon discount in payment gateways.
=> (Fix): Support extra params in payment gateways 

package-lock.json, src/components/access-type.js
Reverts quintype/quintype-node-components#132
=> Revert "(Fix): Support extra params in payment gateways "

package-lock.json, src/components/access-type.js
Reverts quintype/quintype-node-components#134
Talked to Deo and clarify uncertainty.  After discussion we come with the solution that there is no harm adding this commit back to master.
=> Revert "Revert "(Fix): Support extra params in payment gateways ""

package-lock.json, package.json, src/components/story-elements/table.js
fix for https://github.com/quintype/madrid/issues/2273
discussion - https://github.com/quintype/itsman/issues/5304#issuecomment-622666925
=> Use papaparse for table element.

package-lock.json, package.json, src/components/access-type.js
https://github.com/quintype/madrid/issues/2589
=> Story metering

package-lock.json, package.json, src/components/social-logins/with-social-login.js
=> Fix:Update documentation

package-lock.json, package.json, src/components/social-logins/with-social-login.js
Added support for redirect-url in `bridgekeeperServerLoginPath`.
Fixes #  https://github.com/quintype/ace-planning/issues/257
Dependencies # NA
Documentation # NA
Released a beta version and tested it with malibu advanced, 
NL Client also tested it on beta
=> Social login bk

package-lock.json, package.json, src/components/access-type.js
Parameterized the staging and prod hosts in accesstype.js. Now the hosts are configurable. 
Refererence to the issue-> https://github.com/quintype/ace-planning/issues/345
=> Staging and Prod hosts are parameterized in accesstype.js

package-lock.json, package.json, src/components/dfp-ad.js
Fixes # https://github.com/quintype/madrid/issues/3601
=> feat(deferAds): defer gpt.js script load by deferAdsBy(millisecs) prop

package-lock.json, package.json, src/components/access-type.js
Improve the docs of  Accesstype component
https://github.com/quintype/ace-planning/issues/353
=> docs(AccessType) :  Improve the docs of Accesstype component

jest.config.js, jestPreprocess.js, package-lock.json, package.json, src/components/__snapshots__/responsive-image.spec.js.snap, src/components/image-gallery.js, src/components/responsive-image.spec.js
Reference: https://github.com/quintype/ace-planning/issues/644
=> add configuration for imgParams in ImageGalleryElement component

package-lock.json, package.json, src/components/responsive-hero-image.js
fix - https://github.com/quintype/page-builder/issues/1949
=> fix(ResponsiveHeroImage) : Support alt prop

package-lock.json, package.json, src/components/story-element.js, src/components/story-elements/dailymotion-embed-script.js
https://github.com/quintype/madrid/issues/4708
=> feat(dailymotion): support new daily motion subtype

package-lock.json, package.json, src/components/story-elements/jsembed.js
https://github.com/quintype/page-builder/issues/2128
=> chore: add class for jsembed component

package-lock.json, package.json, src/components/access-type.js
Fixes - https://github.com/quintype/madrid/issues/4703
=> feat(paytrail): Integrate Paytrail payment gateway

package-lock.json, package.json, src/components/story-elements/youtube.js
fixes https://github.com/quintype/page-builder/issues/2170
https://github.com/quintype/page-builder/issues/2170#issuecomment-1377169772
This fixes the thumbnail overlap with youtube player issue
=> fix(youtube): yt video ipad issue

package-lock.json, package.json, src/components/access-type.js
Fixes - https://github.com/quintype/page-builder/issues/2199
=> fix(metadata) : Support metadata in subscription plan

package-lock.json, package.json, src/components/access-type.js, src/components/access-type.spec.js, src/components/loading-indicator.js
=> fix: introduce new prop to know AT has loaded

package-lock.json, package.json, src/components/access-type.js
=> fix: call callback if at script already available

package-lock.json, package.json, src/components/story-element.js, src/components/story-elements/brightcove.js
Fixes https://github.com/quintype/page-builder/issues/2349
Dependencies https://github.com/quintype/itsman/issues/10510
=> feat(story element): support brightcove

package-lock.json, package.json, src/components/access-type.js
fix:https://github.com/quintype/page-builder/issues/2489
=> fix(omise): support navigation after subscription purchase

package-lock.json, package.json, src/components/story-elements/brightcove.js, src/components/story-elements/dailymotion-embed-script.js, src/components/story-elements/dailymotion.js, src/components/story-elements/youtube.js, src/utils.js
fixes: https://github.com/quintype/page-builder/issues/2341
=> fix(videos):play/pause videos on visibility 

bin-dev-scripts/standard-version-release.sh, package-lock.json, package.json, src/components/story-elements/jsembed.js
[Ticket](https://github.com/quintype/page-builder/issues/2684)
=> Fix fb video crop

package-lock.json, package.json, src/components/access-type.js
https://github.com/quintype/page-builder/issues/2742
=> Upgrade downgrade

package-lock.json, package.json, src/components/story-elements/table.js
fixes: https://github.com/quintype/page-builder/issues/3141
=> fix(table element): fix table elements column order

package-lock.json, package.json, src/components/social-share.js
fix: https://github.com/quintype/page-builder/issues/3086
=> feat(Social Share): support reddit share

package-lock.json, package.json, src/components/impl/gumlet-image.js, src/components/impl/thumbor-image.js
Ticket: https://github.com/quintype/page-builder/issues/3344
=> Implement preloading of above-fold images on madrid 

.prettierrc, package-lock.json, package.json, src/components/impl/gumlet-image.js, src/components/impl/thumbor-image.js, src/components/responsive-image.js, src/components/responsive-image.spec.js
Ticket: https://github.com/quintype/page-builder/issues/3351
=> feat(Image sizes): add sizes attribute to story page images

package-lock.json, package.json, src/components/impl/gumlet-image.js, src/components/impl/thumbor-image.js
Ticket: https://github.com/quintype/page-builder/issues/3400
=> feat(preload images): preload hero images on story pages

package-lock.json, package.json, src/components/story-elements/youtube.js
https://github.com/quintype/page-builder/issues/3603
=> fix(Youtube button): update icon according to youtube polocies

CHANGELOG.md, package-lock.json, package.json, src/components/access-type.js
fix: https://github.com/quintype/page-builder/issues/3686
=> fix(AT): execute subscription sequential calls based on prop

package-lock.json, package.json, src/components/access-type.js
fix: https://github.com/quintype/page-builder/issues/3686
=>  feat(AT): invoke a prop function when the user is set

package-lock.json, package.json, src/components/impl/thumbor-image.js
=> Decode image
